"""add: budgets + expense_types + expense_reports + budget_adjustments

Revision ID: 2c41209e5408
Revises: 9f2409dd4266
Create Date: 2026-06-06 22:38:05.596084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c41209e5408'
down_revision: Union[str, Sequence[str], None] = '9f2409dd4266'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expense_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False, comment='费用类型名称'),
    sa.Column('code', sa.String(length=20), nullable=False, comment='编码（如 TRAVEL）'),
    sa.Column('description', sa.String(length=200), nullable=True, comment='说明'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('budgets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False, comment='预算归属部门'),
    sa.Column('expense_type_id', sa.Integer(), nullable=False, comment='费用类型'),
    sa.Column('year', sa.Integer(), nullable=False, comment='预算年度'),
    sa.Column('quarter', sa.Integer(), nullable=True, comment='预算季度(1-4, NULL=年度)'),
    sa.Column('amount', sa.DECIMAL(precision=12, scale=2), nullable=False, comment='预算金额'),
    sa.Column('used_amount', sa.DECIMAL(precision=12, scale=2), nullable=False, comment='已使用金额（冗余字段加速查询）'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='预算状态'),
    sa.Column('created_by', sa.Integer(), nullable=False, comment='创建人'),
    sa.Column('approved_by', sa.Integer(), nullable=True, comment='审批人'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['expense_type_id'], ['expense_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('expense_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('report_no', sa.String(length=30), nullable=False, comment='报销单号'),
    sa.Column('submitter_id', sa.Integer(), nullable=False, comment='提交人'),
    sa.Column('department_id', sa.Integer(), nullable=False, comment='所属部门'),
    sa.Column('expense_type_id', sa.Integer(), nullable=False, comment='费用类型'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='报销事由'),
    sa.Column('amount', sa.DECIMAL(precision=12, scale=2), nullable=False, comment='报销金额'),
    sa.Column('description', sa.String(length=500), nullable=True, comment='详细说明'),
    sa.Column('attachment_path', sa.String(length=500), nullable=True, comment='附件路径'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='报销单状态'),
    sa.Column('current_approver_id', sa.Integer(), nullable=True, comment='当前审批人'),
    sa.Column('submitted_at', sa.DateTime(), nullable=True, comment='提交时间'),
    sa.Column('settled_at', sa.DateTime(), nullable=True, comment='完成时间'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['current_approver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['expense_type_id'], ['expense_types.id'], ),
    sa.ForeignKeyConstraint(['submitter_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_no')
    )
    op.create_table('budget_adjustments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('budget_id', sa.Integer(), nullable=False, comment='关联预算'),
    sa.Column('adjustment_amount', sa.DECIMAL(precision=12, scale=2), nullable=False, comment='调整金额（正=追加，负=调减）'),
    sa.Column('reason', sa.String(length=500), nullable=False, comment='调整原因'),
    sa.Column('created_by', sa.Integer(), nullable=False, comment='操作人'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['budget_id'], ['budgets.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('budget_adjustments')
    op.drop_table('expense_reports')
    op.drop_table('budgets')
    op.drop_table('expense_types')
    # ### end Alembic commands ###
