"""add: approval_records

Revision ID: f3ea96aebcdb
Revises: 2c41209e5408
Create Date: 2026-06-06 22:48:45.050100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3ea96aebcdb'
down_revision: Union[str, Sequence[str], None] = '2c41209e5408'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approval_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('target_type', sa.String(length=30), nullable=False, comment='审批目标类型'),
    sa.Column('target_id', sa.Integer(), nullable=False, comment='审批目标ID'),
    sa.Column('approver_id', sa.Integer(), nullable=False, comment='审批人'),
    sa.Column('level', sa.Integer(), nullable=False, comment='审批级别'),
    sa.Column('action', sa.String(length=20), nullable=False, comment='操作: approved/rejected'),
    sa.Column('comment', sa.String(length=500), nullable=True, comment='审批意见'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['approver_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('approval_records')
    # ### end Alembic commands ###
